name: CI

on:
  push:
    branches:
      - main
      - master
    tags:
      - "v*.*.*"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  linux_tests:
    name: Run tests on Linux (${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install uv
          uv sync --system

      - name: Run linter and formatter
        run: |
          uvx ruff check . --fix --exit-non-zero-on-fix
          uvx ruff format . --check

      - name: Run tests (if any)
        run: echo "No tests configured"

  build_package:
    name: Build source and wheel distributions
    runs-on: ubuntu-latest
    needs: linux_tests
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install build dependencies
        run: python -m pip install build

      - name: Build distributions
        run: python -m build

      - name: Upload distributions as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish-to-pypi:
    name: Publish package to PyPI
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: build_package
    environment:
      name: pypi
      url: https://pypi.org/p/gdrive-suite
    permissions:
      id-token: write

    steps:
      - name: Download distributions from build job
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
